import { NextRequest, NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabase/server';
import { RouteAccessError, requireProjectOwner } from '@/lib/api/route-auth';

// Helper function to generate keywords from speaker name for matching
function generateKeywordsFromName(name: string): string[] {
  const parts = name.toLowerCase().split(/\s+/).filter(p => p.length > 1);
  const keywords = [...parts, name.toLowerCase()];

  // Add "first last-initial" pattern (e.g., "john s")
  if (parts.length >= 2) {
    keywords.push(`${parts[0]} ${parts[parts.length - 1][0]}`);
  }

  // Add first name variations
  if (parts.length > 0) {
    keywords.push(parts[0]); // First name alone
  }

  return [...new Set(keywords)];
}

// GET roster speakers for a project
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id: projectId } = await params;
    await requireProjectOwner(request, projectId, 'preset_speakers, speaker_keywords');

    const { data, error } = await supabaseAdmin
      .from('projects')
      .select('preset_speakers, speaker_keywords')
      .eq('id', projectId)
      .single() as { data: { preset_speakers: any; speaker_keywords: any } | null; error: any };

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({
      rosterSpeakers: data?.preset_speakers || [],
      keywords: data?.speaker_keywords || []
    });

  } catch (error: any) {
    if (error instanceof RouteAccessError) {
      return NextResponse.json({ error: error.message }, { status: error.status });
    }
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

// PATCH update roster speakers (pre-transcription)
export async function PATCH(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id: projectId } = await params;
    const { rosterSpeakers } = await request.json();
    const { user } = await requireProjectOwner(request, projectId);

    if (!Array.isArray(rosterSpeakers)) {
      return NextResponse.json({ error: 'Invalid roster format' }, { status: 400 });
    }

    if (user.email === process.env.DEMO_EMAIL) {
      return NextResponse.json({ error: 'Demo account is read-only' }, { status: 403 });
    }

    // Validate speakers
    for (const speaker of rosterSpeakers) {
      if (!speaker.name || speaker.name.trim().length < 2) {
        return NextResponse.json({ error: 'Speaker name must be at least 2 characters' }, { status: 400 });
      }
    }

    // Auto-generate keywords
    const keywords = rosterSpeakers.map(speaker => ({
      rosterSpeakerId: speaker.id,
      keywords: generateKeywordsFromName(speaker.name),
      autoGenerated: true
    }));

    const { error } = await (supabaseAdmin
      .from('projects') as any)
      .update({
        preset_speakers: rosterSpeakers,
        speaker_keywords: keywords
      })
      .eq('id', projectId);

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({ success: true });

  } catch (error: any) {
    if (error instanceof RouteAccessError) {
      return NextResponse.json({ error: error.message }, { status: error.status });
    }
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
