import { NextRequest, NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabase/server';
import { importRecording } from '@/lib/integrations/importer';
import {
  validatePublicUrl,
  isYouTubeUrl,
  downloadYouTubeAudio,
  downloadDirectMedia,
  extractAudioFromVideoBuffer
} from '@/lib/url-importer';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

type PerformanceLevel = 'standard' | 'pro';

const normalizePerformanceLevel = (value?: string | null): PerformanceLevel => {
  if (value === 'standard' || value === 'pro') return value;
  if (value === 'basic' || value === 'low') return 'standard';
  if (value === 'premium' || value === 'high' || value === 'medium') return 'pro';
  return 'pro';
};

const sanitizeTitle = (title: string) => {
  const trimmed = title.trim();
  return trimmed.length ? trimmed : 'URL import';
};

const getTitleFromFileName = (name: string) => {
  const cleaned = name.replace(/\.[^/.]+$/, '').replace(/[_-]+/g, ' ').trim();
  return cleaned || 'URL import';
};

const generateKeywordsFromName = (name: string): string[] => {
  const parts = name.toLowerCase().split(/\s+/).filter(p => p.length > 1);
  const keywords = [...parts, name.toLowerCase()];

  if (parts.length >= 2) {
    keywords.push(`${parts[0]} ${parts[parts.length - 1][0]}`);
  }

  if (parts.length > 0) {
    keywords.push(parts[0]);
  }

  return [...new Set(keywords)];
};

export async function POST(request: NextRequest) {
  try {
    const authHeader = request.headers.get('authorization');
    const { data: { user }, error: authError } = await supabaseAdmin.auth.getUser(
      authHeader?.replace('Bearer ', '') || ''
    );

    if (authError || !user) {
      return NextResponse.json({ error: 'Authentication required' }, { status: 401 });
    }

    const body = await request.json();
    const url = typeof body?.url === 'string' ? body.url.trim() : '';
    const titleInput = typeof body?.title === 'string' ? body.title : '';
    const performanceLevel = normalizePerformanceLevel(body?.performanceLevel);
    const speakerCount = typeof body?.speakerCount === 'number' ? body.speakerCount : undefined;
    const rosterSpeakers = Array.isArray(body?.rosterSpeakers) ? body.rosterSpeakers : undefined;

    if (!url) {
      return NextResponse.json({ error: 'URL is required' }, { status: 400 });
    }

    await validatePublicUrl(url);

    let buffer: ArrayBuffer;
    let contentType = 'audio/mpeg';
    let fileName = 'url-import.mp3';
    let title = titleInput;

    if (isYouTubeUrl(url)) {
      const yt = await downloadYouTubeAudio(url);
      buffer = yt.buffer;
      contentType = yt.contentType;
      fileName = yt.fileName;
      title = title || yt.title;
    } else {
      const direct = await downloadDirectMedia(url);
      fileName = direct.fileName;
      contentType = direct.contentType;
      buffer = direct.buffer;

      if (direct.isVideo) {
        const audio = await extractAudioFromVideoBuffer(buffer);
        buffer = audio.buffer;
        contentType = audio.contentType;
        fileName = `${getTitleFromFileName(fileName)}.mp3`;
      }
    }

    const finalTitle = sanitizeTitle(title || getTitleFromFileName(fileName));

    const importResult = await importRecording({
      userId: user.id,
      title: finalTitle,
      fileName,
      contentType,
      buffer,
      performanceLevel,
      speakerCount,
      externalSource: {
        provider: isYouTubeUrl(url) ? 'youtube' : 'direct',
        recordingId: url
      }
    });

    if (rosterSpeakers?.length) {
      try {
        const keywords = rosterSpeakers.map((speaker: any) => ({
          rosterSpeakerId: speaker.id,
          keywords: generateKeywordsFromName(speaker.name),
          autoGenerated: true
        }));

        await (supabaseAdmin
          .from('projects') as any)
          .update({
            preset_speakers: rosterSpeakers,
            speaker_keywords: keywords
          })
          .eq('id', importResult.projectId);
      } catch {
        // Non-fatal for URL imports
      }
    }

    return NextResponse.json({
      success: true,
      projectId: importResult.projectId,
      title: finalTitle
    });
  } catch (error) {
    console.error('[URL IMPORT] Failed:', error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'URL import failed' },
      { status: 500 }
    );
  }
}
